version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    volumes:
      - "./elastic/jvm.options:/usr/share/elasticsearch/config/jvm.options:ro"
      - "./elastic/elastic.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.4
    volumes:
      - "./logstash/pipeline/:/usr/share/logstash/pipeline:ro"
      - "./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro"
    ports:
      - "2112:2112"
    depends_on:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    volumes:
      - "./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    ports:
      - "5601:5601"
    depends_on:
      - elastic
